#!/bin/bash

# Arquivo temporário que armazena a mensagem
COMMIT_MSG_FILE=$1

# Regex para validar o padrão: TIPO: Descrição
# Tipos permitidos: FEAT, FIX, TASK, CHORE
PATTERN="^(FEAT|FIX|TASK|CHORE): .+"

COMMIT_MSG=$(cat $COMMIT_MSG_FILE)

if [[ ! $COMMIT_MSG =~ $PATTERN ]]; then
  echo -e "\n\033[31m❌ ERRO: Mensagem de commit inválida!\033[0m"
  echo "-------------------------------------------------------"
  echo "Sua mensagem deve seguir o padrão: TIPO: Descrição"
  echo "Exemplo: FEAT: Adicionando integração com API de pagamentos"
  echo "-------------------------------------------------------"
  exit 1
fi
